// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global.proto

package org.shell.mmo.sample.message.proto;

public final class Global {
  private Global() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code org.shell.mmo.sample.message.proto.Error}
   *
   * <pre>
   * 错误码
   * </pre>
   */
  public enum Error
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SYS_ERR = 1;</code>
     *
     * <pre>
     * 系统错误
     * </pre>
     */
    SYS_ERR(0, 1),
    ;

    /**
     * <code>SYS_ERR = 1;</code>
     *
     * <pre>
     * 系统错误
     * </pre>
     */
    public static final int SYS_ERR_VALUE = 1;


    public final int getNumber() { return value; }

    public static Error valueOf(int value) {
      switch (value) {
        case 1: return SYS_ERR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Error>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Error>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Error>() {
            public Error findValueByNumber(int number) {
              return Error.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.shell.mmo.sample.message.proto.Global.getDescriptor().getEnumTypes().get(0);
    }

    private static final Error[] VALUES = values();

    public static Error valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Error(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.shell.mmo.sample.message.proto.Error)
  }

  /**
   * Protobuf enum {@code org.shell.mmo.sample.message.proto.GameObjectType}
   *
   * <pre>
   * 对象类型
   * </pre>
   */
  public enum GameObjectType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HERO = 1;</code>
     *
     * <pre>
     * 英雄
     * </pre>
     */
    HERO(0, 1),
    /**
     * <code>MONSTER = 2;</code>
     *
     * <pre>
     * 怪物
     * </pre>
     */
    MONSTER(1, 2),
    /**
     * <code>PET = 3;</code>
     *
     * <pre>
     * 宠物
     * </pre>
     */
    PET(2, 3),
    /**
     * <code>ITEM = 4;</code>
     *
     * <pre>
     * 道具
     * </pre>
     */
    ITEM(3, 4),
    ;

    /**
     * <code>HERO = 1;</code>
     *
     * <pre>
     * 英雄
     * </pre>
     */
    public static final int HERO_VALUE = 1;
    /**
     * <code>MONSTER = 2;</code>
     *
     * <pre>
     * 怪物
     * </pre>
     */
    public static final int MONSTER_VALUE = 2;
    /**
     * <code>PET = 3;</code>
     *
     * <pre>
     * 宠物
     * </pre>
     */
    public static final int PET_VALUE = 3;
    /**
     * <code>ITEM = 4;</code>
     *
     * <pre>
     * 道具
     * </pre>
     */
    public static final int ITEM_VALUE = 4;


    public final int getNumber() { return value; }

    public static GameObjectType valueOf(int value) {
      switch (value) {
        case 1: return HERO;
        case 2: return MONSTER;
        case 3: return PET;
        case 4: return ITEM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameObjectType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameObjectType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameObjectType>() {
            public GameObjectType findValueByNumber(int number) {
              return GameObjectType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.shell.mmo.sample.message.proto.Global.getDescriptor().getEnumTypes().get(1);
    }

    private static final GameObjectType[] VALUES = values();

    public static GameObjectType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GameObjectType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.shell.mmo.sample.message.proto.GameObjectType)
  }

  /**
   * Protobuf enum {@code org.shell.mmo.sample.message.proto.Module}
   *
   * <pre>
   * 模块类型
   * </pre>
   */
  public enum Module
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN = 1;</code>
     *
     * <pre>
     * 登录
     * </pre>
     */
    LOGIN(0, 1),
    /**
     * <code>FIGHT = 2;</code>
     *
     * <pre>
     * 战斗
     * </pre>
     */
    FIGHT(1, 2),
    /**
     * <code>MOVE = 3;</code>
     *
     * <pre>
     * 移动
     * </pre>
     */
    MOVE(2, 3),
    ;

    /**
     * <code>LOGIN = 1;</code>
     *
     * <pre>
     * 登录
     * </pre>
     */
    public static final int LOGIN_VALUE = 1;
    /**
     * <code>FIGHT = 2;</code>
     *
     * <pre>
     * 战斗
     * </pre>
     */
    public static final int FIGHT_VALUE = 2;
    /**
     * <code>MOVE = 3;</code>
     *
     * <pre>
     * 移动
     * </pre>
     */
    public static final int MOVE_VALUE = 3;


    public final int getNumber() { return value; }

    public static Module valueOf(int value) {
      switch (value) {
        case 1: return LOGIN;
        case 2: return FIGHT;
        case 3: return MOVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Module>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Module>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Module>() {
            public Module findValueByNumber(int number) {
              return Module.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.shell.mmo.sample.message.proto.Global.getDescriptor().getEnumTypes().get(2);
    }

    private static final Module[] VALUES = values();

    public static Module valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Module(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.shell.mmo.sample.message.proto.Module)
  }

  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.shell.mmo.sample.message.proto.Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 x = 1;</code>
     *
     * <pre>
     * 横坐标
     * </pre>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 1;</code>
     *
     * <pre>
     * 横坐标
     * </pre>
     */
    int getX();

    /**
     * <code>required int32 y = 2;</code>
     *
     * <pre>
     * 纵坐标
     * </pre>
     */
    boolean hasY();
    /**
     * <code>required int32 y = 2;</code>
     *
     * <pre>
     * 纵坐标
     * </pre>
     */
    int getY();
  }
  /**
   * Protobuf type {@code org.shell.mmo.sample.message.proto.Position}
   *
   * <pre>
   * 坐标
   * </pre>
   */
  public static final class Position extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.shell.mmo.sample.message.proto.Position)
      PositionOrBuilder {
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Position(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Position defaultInstance;
    public static Position getDefaultInstance() {
      return defaultInstance;
    }

    public Position getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.shell.mmo.sample.message.proto.Global.internal_static_org_shell_mmo_sample_message_proto_Position_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.shell.mmo.sample.message.proto.Global.internal_static_org_shell_mmo_sample_message_proto_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.shell.mmo.sample.message.proto.Global.Position.class, org.shell.mmo.sample.message.proto.Global.Position.Builder.class);
    }

    public static com.google.protobuf.Parser<Position> PARSER =
        new com.google.protobuf.AbstractParser<Position>() {
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Position(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>required int32 x = 1;</code>
     *
     * <pre>
     * 横坐标
     * </pre>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 x = 1;</code>
     *
     * <pre>
     * 横坐标
     * </pre>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>required int32 y = 2;</code>
     *
     * <pre>
     * 纵坐标
     * </pre>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 y = 2;</code>
     *
     * <pre>
     * 纵坐标
     * </pre>
     */
    public int getY() {
      return y_;
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.shell.mmo.sample.message.proto.Global.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shell.mmo.sample.message.proto.Global.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.Global.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shell.mmo.sample.message.proto.Global.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.Global.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.Global.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.Global.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.Global.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.Global.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.Global.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.shell.mmo.sample.message.proto.Global.Position prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.shell.mmo.sample.message.proto.Position}
     *
     * <pre>
     * 坐标
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.shell.mmo.sample.message.proto.Position)
        org.shell.mmo.sample.message.proto.Global.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.shell.mmo.sample.message.proto.Global.internal_static_org_shell_mmo_sample_message_proto_Position_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.shell.mmo.sample.message.proto.Global.internal_static_org_shell_mmo_sample_message_proto_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.shell.mmo.sample.message.proto.Global.Position.class, org.shell.mmo.sample.message.proto.Global.Position.Builder.class);
      }

      // Construct using org.shell.mmo.sample.message.proto.Global.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.shell.mmo.sample.message.proto.Global.internal_static_org_shell_mmo_sample_message_proto_Position_descriptor;
      }

      public org.shell.mmo.sample.message.proto.Global.Position getDefaultInstanceForType() {
        return org.shell.mmo.sample.message.proto.Global.Position.getDefaultInstance();
      }

      public org.shell.mmo.sample.message.proto.Global.Position build() {
        org.shell.mmo.sample.message.proto.Global.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.shell.mmo.sample.message.proto.Global.Position buildPartial() {
        org.shell.mmo.sample.message.proto.Global.Position result = new org.shell.mmo.sample.message.proto.Global.Position(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.shell.mmo.sample.message.proto.Global.Position) {
          return mergeFrom((org.shell.mmo.sample.message.proto.Global.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.shell.mmo.sample.message.proto.Global.Position other) {
        if (other == org.shell.mmo.sample.message.proto.Global.Position.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.shell.mmo.sample.message.proto.Global.Position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.shell.mmo.sample.message.proto.Global.Position) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int x_ ;
      /**
       * <code>required int32 x = 1;</code>
       *
       * <pre>
       * 横坐标
       * </pre>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1;</code>
       *
       * <pre>
       * 横坐标
       * </pre>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 1;</code>
       *
       * <pre>
       * 横坐标
       * </pre>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 1;</code>
       *
       * <pre>
       * 横坐标
       * </pre>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>required int32 y = 2;</code>
       *
       * <pre>
       * 纵坐标
       * </pre>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 y = 2;</code>
       *
       * <pre>
       * 纵坐标
       * </pre>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required int32 y = 2;</code>
       *
       * <pre>
       * 纵坐标
       * </pre>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 y = 2;</code>
       *
       * <pre>
       * 纵坐标
       * </pre>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.shell.mmo.sample.message.proto.Position)
    }

    static {
      defaultInstance = new Position(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.shell.mmo.sample.message.proto.Position)
  }

  public interface LeaderRoleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.shell.mmo.sample.message.proto.LeaderRole)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required fixed64 id = 1;</code>
     *
     * <pre>
     * 角色id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required fixed64 id = 1;</code>
     *
     * <pre>
     * 角色id
     * </pre>
     */
    long getId();

    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 名字
     * </pre>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 名字
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 名字
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 map = 3;</code>
     *
     * <pre>
     * 地图
     * </pre>
     */
    boolean hasMap();
    /**
     * <code>required int32 map = 3;</code>
     *
     * <pre>
     * 地图
     * </pre>
     */
    int getMap();

    /**
     * <code>required int32 level = 4;</code>
     *
     * <pre>
     * 等级
     * </pre>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 4;</code>
     *
     * <pre>
     * 等级
     * </pre>
     */
    int getLevel();

    /**
     * <code>required int32 server = 5;</code>
     *
     * <pre>
     * 服务器
     * </pre>
     */
    boolean hasServer();
    /**
     * <code>required int32 server = 5;</code>
     *
     * <pre>
     * 服务器
     * </pre>
     */
    int getServer();

    /**
     * <code>required int32 platform = 6;</code>
     *
     * <pre>
     * 平台
     * </pre>
     */
    boolean hasPlatform();
    /**
     * <code>required int32 platform = 6;</code>
     *
     * <pre>
     * 平台
     * </pre>
     */
    int getPlatform();

    /**
     * <code>required int32 gold = 7;</code>
     *
     * <pre>
     * 元宝
     * </pre>
     */
    boolean hasGold();
    /**
     * <code>required int32 gold = 7;</code>
     *
     * <pre>
     * 元宝
     * </pre>
     */
    int getGold();
  }
  /**
   * Protobuf type {@code org.shell.mmo.sample.message.proto.LeaderRole}
   *
   * <pre>
   * 主角
   * </pre>
   */
  public static final class LeaderRole extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.shell.mmo.sample.message.proto.LeaderRole)
      LeaderRoleOrBuilder {
    // Use LeaderRole.newBuilder() to construct.
    private LeaderRole(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LeaderRole(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LeaderRole defaultInstance;
    public static LeaderRole getDefaultInstance() {
      return defaultInstance;
    }

    public LeaderRole getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LeaderRole(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              id_ = input.readFixed64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              map_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              level_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              server_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              platform_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              gold_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.shell.mmo.sample.message.proto.Global.internal_static_org_shell_mmo_sample_message_proto_LeaderRole_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.shell.mmo.sample.message.proto.Global.internal_static_org_shell_mmo_sample_message_proto_LeaderRole_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.shell.mmo.sample.message.proto.Global.LeaderRole.class, org.shell.mmo.sample.message.proto.Global.LeaderRole.Builder.class);
    }

    public static com.google.protobuf.Parser<LeaderRole> PARSER =
        new com.google.protobuf.AbstractParser<LeaderRole>() {
      public LeaderRole parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeaderRole(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LeaderRole> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required fixed64 id = 1;</code>
     *
     * <pre>
     * 角色id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required fixed64 id = 1;</code>
     *
     * <pre>
     * 角色id
     * </pre>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 名字
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 名字
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 名字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAP_FIELD_NUMBER = 3;
    private int map_;
    /**
     * <code>required int32 map = 3;</code>
     *
     * <pre>
     * 地图
     * </pre>
     */
    public boolean hasMap() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 map = 3;</code>
     *
     * <pre>
     * 地图
     * </pre>
     */
    public int getMap() {
      return map_;
    }

    public static final int LEVEL_FIELD_NUMBER = 4;
    private int level_;
    /**
     * <code>required int32 level = 4;</code>
     *
     * <pre>
     * 等级
     * </pre>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 level = 4;</code>
     *
     * <pre>
     * 等级
     * </pre>
     */
    public int getLevel() {
      return level_;
    }

    public static final int SERVER_FIELD_NUMBER = 5;
    private int server_;
    /**
     * <code>required int32 server = 5;</code>
     *
     * <pre>
     * 服务器
     * </pre>
     */
    public boolean hasServer() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 server = 5;</code>
     *
     * <pre>
     * 服务器
     * </pre>
     */
    public int getServer() {
      return server_;
    }

    public static final int PLATFORM_FIELD_NUMBER = 6;
    private int platform_;
    /**
     * <code>required int32 platform = 6;</code>
     *
     * <pre>
     * 平台
     * </pre>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 platform = 6;</code>
     *
     * <pre>
     * 平台
     * </pre>
     */
    public int getPlatform() {
      return platform_;
    }

    public static final int GOLD_FIELD_NUMBER = 7;
    private int gold_;
    /**
     * <code>required int32 gold = 7;</code>
     *
     * <pre>
     * 元宝
     * </pre>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 gold = 7;</code>
     *
     * <pre>
     * 元宝
     * </pre>
     */
    public int getGold() {
      return gold_;
    }

    private void initFields() {
      id_ = 0L;
      name_ = "";
      map_ = 0;
      level_ = 0;
      server_ = 0;
      platform_ = 0;
      gold_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMap()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlatform()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, map_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, level_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, server_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, platform_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, gold_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, map_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, level_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, server_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, platform_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, gold_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.shell.mmo.sample.message.proto.Global.LeaderRole parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shell.mmo.sample.message.proto.Global.LeaderRole parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.Global.LeaderRole parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shell.mmo.sample.message.proto.Global.LeaderRole parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.Global.LeaderRole parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.Global.LeaderRole parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.Global.LeaderRole parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.Global.LeaderRole parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.Global.LeaderRole parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.Global.LeaderRole parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.shell.mmo.sample.message.proto.Global.LeaderRole prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.shell.mmo.sample.message.proto.LeaderRole}
     *
     * <pre>
     * 主角
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.shell.mmo.sample.message.proto.LeaderRole)
        org.shell.mmo.sample.message.proto.Global.LeaderRoleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.shell.mmo.sample.message.proto.Global.internal_static_org_shell_mmo_sample_message_proto_LeaderRole_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.shell.mmo.sample.message.proto.Global.internal_static_org_shell_mmo_sample_message_proto_LeaderRole_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.shell.mmo.sample.message.proto.Global.LeaderRole.class, org.shell.mmo.sample.message.proto.Global.LeaderRole.Builder.class);
      }

      // Construct using org.shell.mmo.sample.message.proto.Global.LeaderRole.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        map_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        server_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        platform_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.shell.mmo.sample.message.proto.Global.internal_static_org_shell_mmo_sample_message_proto_LeaderRole_descriptor;
      }

      public org.shell.mmo.sample.message.proto.Global.LeaderRole getDefaultInstanceForType() {
        return org.shell.mmo.sample.message.proto.Global.LeaderRole.getDefaultInstance();
      }

      public org.shell.mmo.sample.message.proto.Global.LeaderRole build() {
        org.shell.mmo.sample.message.proto.Global.LeaderRole result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.shell.mmo.sample.message.proto.Global.LeaderRole buildPartial() {
        org.shell.mmo.sample.message.proto.Global.LeaderRole result = new org.shell.mmo.sample.message.proto.Global.LeaderRole(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.map_ = map_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.server_ = server_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.platform_ = platform_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.gold_ = gold_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.shell.mmo.sample.message.proto.Global.LeaderRole) {
          return mergeFrom((org.shell.mmo.sample.message.proto.Global.LeaderRole)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.shell.mmo.sample.message.proto.Global.LeaderRole other) {
        if (other == org.shell.mmo.sample.message.proto.Global.LeaderRole.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMap()) {
          setMap(other.getMap());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasServer()) {
          setServer(other.getServer());
        }
        if (other.hasPlatform()) {
          setPlatform(other.getPlatform());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasMap()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasServer()) {
          
          return false;
        }
        if (!hasPlatform()) {
          
          return false;
        }
        if (!hasGold()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.shell.mmo.sample.message.proto.Global.LeaderRole parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.shell.mmo.sample.message.proto.Global.LeaderRole) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required fixed64 id = 1;</code>
       *
       * <pre>
       * 角色id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed64 id = 1;</code>
       *
       * <pre>
       * 角色id
       * </pre>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required fixed64 id = 1;</code>
       *
       * <pre>
       * 角色id
       * </pre>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 id = 1;</code>
       *
       * <pre>
       * 角色id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 名字
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 名字
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 名字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 名字
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 名字
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 名字
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int map_ ;
      /**
       * <code>required int32 map = 3;</code>
       *
       * <pre>
       * 地图
       * </pre>
       */
      public boolean hasMap() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 map = 3;</code>
       *
       * <pre>
       * 地图
       * </pre>
       */
      public int getMap() {
        return map_;
      }
      /**
       * <code>required int32 map = 3;</code>
       *
       * <pre>
       * 地图
       * </pre>
       */
      public Builder setMap(int value) {
        bitField0_ |= 0x00000004;
        map_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 map = 3;</code>
       *
       * <pre>
       * 地图
       * </pre>
       */
      public Builder clearMap() {
        bitField0_ = (bitField0_ & ~0x00000004);
        map_ = 0;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>required int32 level = 4;</code>
       *
       * <pre>
       * 等级
       * </pre>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 level = 4;</code>
       *
       * <pre>
       * 等级
       * </pre>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 4;</code>
       *
       * <pre>
       * 等级
       * </pre>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000008;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 4;</code>
       *
       * <pre>
       * 等级
       * </pre>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        onChanged();
        return this;
      }

      private int server_ ;
      /**
       * <code>required int32 server = 5;</code>
       *
       * <pre>
       * 服务器
       * </pre>
       */
      public boolean hasServer() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 server = 5;</code>
       *
       * <pre>
       * 服务器
       * </pre>
       */
      public int getServer() {
        return server_;
      }
      /**
       * <code>required int32 server = 5;</code>
       *
       * <pre>
       * 服务器
       * </pre>
       */
      public Builder setServer(int value) {
        bitField0_ |= 0x00000010;
        server_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 server = 5;</code>
       *
       * <pre>
       * 服务器
       * </pre>
       */
      public Builder clearServer() {
        bitField0_ = (bitField0_ & ~0x00000010);
        server_ = 0;
        onChanged();
        return this;
      }

      private int platform_ ;
      /**
       * <code>required int32 platform = 6;</code>
       *
       * <pre>
       * 平台
       * </pre>
       */
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 platform = 6;</code>
       *
       * <pre>
       * 平台
       * </pre>
       */
      public int getPlatform() {
        return platform_;
      }
      /**
       * <code>required int32 platform = 6;</code>
       *
       * <pre>
       * 平台
       * </pre>
       */
      public Builder setPlatform(int value) {
        bitField0_ |= 0x00000020;
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 platform = 6;</code>
       *
       * <pre>
       * 平台
       * </pre>
       */
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000020);
        platform_ = 0;
        onChanged();
        return this;
      }

      private int gold_ ;
      /**
       * <code>required int32 gold = 7;</code>
       *
       * <pre>
       * 元宝
       * </pre>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 gold = 7;</code>
       *
       * <pre>
       * 元宝
       * </pre>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>required int32 gold = 7;</code>
       *
       * <pre>
       * 元宝
       * </pre>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000040;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gold = 7;</code>
       *
       * <pre>
       * 元宝
       * </pre>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000040);
        gold_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.shell.mmo.sample.message.proto.LeaderRole)
    }

    static {
      defaultInstance = new LeaderRole(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.shell.mmo.sample.message.proto.LeaderRole)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_shell_mmo_sample_message_proto_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_shell_mmo_sample_message_proto_Position_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_shell_mmo_sample_message_proto_LeaderRole_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_shell_mmo_sample_message_proto_LeaderRole_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014global.proto\022\"org.shell.mmo.sample.mes" +
      "sage.proto\" \n\010Position\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002" +
      " \002(\005\"r\n\nLeaderRole\022\n\n\002id\030\001 \002(\006\022\014\n\004name\030\002" +
      " \002(\t\022\013\n\003map\030\003 \002(\005\022\r\n\005level\030\004 \002(\005\022\016\n\006serv" +
      "er\030\005 \002(\005\022\020\n\010platform\030\006 \002(\005\022\014\n\004gold\030\007 \002(\005" +
      "*\024\n\005Error\022\013\n\007SYS_ERR\020\001*:\n\016GameObjectType" +
      "\022\010\n\004HERO\020\001\022\013\n\007MONSTER\020\002\022\007\n\003PET\020\003\022\010\n\004ITEM" +
      "\020\004*(\n\006Module\022\t\n\005LOGIN\020\001\022\t\n\005FIGHT\020\002\022\010\n\004MO" +
      "VE\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_shell_mmo_sample_message_proto_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_shell_mmo_sample_message_proto_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_shell_mmo_sample_message_proto_Position_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_org_shell_mmo_sample_message_proto_LeaderRole_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_shell_mmo_sample_message_proto_LeaderRole_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_shell_mmo_sample_message_proto_LeaderRole_descriptor,
        new java.lang.String[] { "Id", "Name", "Map", "Level", "Server", "Platform", "Gold", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
