// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicClient.proto

package org.shell.mmo.sample.message.proto;

public final class LogicClient {
  private LogicClient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqLoginLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.shell.mmo.sample.message.proto.ReqLoginLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string usr = 1;</code>
     *
     * <pre>
     * 账号
     * </pre>
     */
    boolean hasUsr();
    /**
     * <code>optional string usr = 1;</code>
     *
     * <pre>
     * 账号
     * </pre>
     */
    java.lang.String getUsr();
    /**
     * <code>optional string usr = 1;</code>
     *
     * <pre>
     * 账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getUsrBytes();

    /**
     * <code>optional .org.shell.mmo.sample.message.proto.Platform platform = 2;</code>
     *
     * <pre>
     * 平台
     * </pre>
     */
    boolean hasPlatform();
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.Platform platform = 2;</code>
     *
     * <pre>
     * 平台
     * </pre>
     */
    org.shell.mmo.sample.message.proto.Global.Platform getPlatform();

    /**
     * <code>optional int32 server = 3;</code>
     *
     * <pre>
     * 服务器
     * </pre>
     */
    boolean hasServer();
    /**
     * <code>optional int32 server = 3;</code>
     *
     * <pre>
     * 服务器
     * </pre>
     */
    int getServer();

    /**
     * <code>optional bool adult = 4;</code>
     *
     * <pre>
     * 是否成年
     * </pre>
     */
    boolean hasAdult();
    /**
     * <code>optional bool adult = 4;</code>
     *
     * <pre>
     * 是否成年
     * </pre>
     */
    boolean getAdult();

    /**
     * <code>optional int32 time = 5;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>optional int32 time = 5;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    int getTime();

    /**
     * <code>optional string sign = 6;</code>
     *
     * <pre>
     * 验证串
     * </pre>
     */
    boolean hasSign();
    /**
     * <code>optional string sign = 6;</code>
     *
     * <pre>
     * 验证串
     * </pre>
     */
    java.lang.String getSign();
    /**
     * <code>optional string sign = 6;</code>
     *
     * <pre>
     * 验证串
     * </pre>
     */
    com.google.protobuf.ByteString
        getSignBytes();
  }
  /**
   * Protobuf type {@code org.shell.mmo.sample.message.proto.ReqLoginLogin}
   *
   * <pre>
   * 登录:参数
   * </pre>
   */
  public static final class ReqLoginLogin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.shell.mmo.sample.message.proto.ReqLoginLogin)
      ReqLoginLoginOrBuilder {
    // Use ReqLoginLogin.newBuilder() to construct.
    private ReqLoginLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqLoginLogin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqLoginLogin defaultInstance;
    public static ReqLoginLogin getDefaultInstance() {
      return defaultInstance;
    }

    public ReqLoginLogin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqLoginLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              usr_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.shell.mmo.sample.message.proto.Global.Platform value = org.shell.mmo.sample.message.proto.Global.Platform.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                platform_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              server_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              adult_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              time_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              sign_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.shell.mmo.sample.message.proto.LogicClient.internal_static_org_shell_mmo_sample_message_proto_ReqLoginLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.shell.mmo.sample.message.proto.LogicClient.internal_static_org_shell_mmo_sample_message_proto_ReqLoginLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin.class, org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqLoginLogin> PARSER =
        new com.google.protobuf.AbstractParser<ReqLoginLogin>() {
      public ReqLoginLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqLoginLogin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqLoginLogin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USR_FIELD_NUMBER = 1;
    private java.lang.Object usr_;
    /**
     * <code>optional string usr = 1;</code>
     *
     * <pre>
     * 账号
     * </pre>
     */
    public boolean hasUsr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string usr = 1;</code>
     *
     * <pre>
     * 账号
     * </pre>
     */
    public java.lang.String getUsr() {
      java.lang.Object ref = usr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string usr = 1;</code>
     *
     * <pre>
     * 账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUsrBytes() {
      java.lang.Object ref = usr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORM_FIELD_NUMBER = 2;
    private org.shell.mmo.sample.message.proto.Global.Platform platform_;
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.Platform platform = 2;</code>
     *
     * <pre>
     * 平台
     * </pre>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.Platform platform = 2;</code>
     *
     * <pre>
     * 平台
     * </pre>
     */
    public org.shell.mmo.sample.message.proto.Global.Platform getPlatform() {
      return platform_;
    }

    public static final int SERVER_FIELD_NUMBER = 3;
    private int server_;
    /**
     * <code>optional int32 server = 3;</code>
     *
     * <pre>
     * 服务器
     * </pre>
     */
    public boolean hasServer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 server = 3;</code>
     *
     * <pre>
     * 服务器
     * </pre>
     */
    public int getServer() {
      return server_;
    }

    public static final int ADULT_FIELD_NUMBER = 4;
    private boolean adult_;
    /**
     * <code>optional bool adult = 4;</code>
     *
     * <pre>
     * 是否成年
     * </pre>
     */
    public boolean hasAdult() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool adult = 4;</code>
     *
     * <pre>
     * 是否成年
     * </pre>
     */
    public boolean getAdult() {
      return adult_;
    }

    public static final int TIME_FIELD_NUMBER = 5;
    private int time_;
    /**
     * <code>optional int32 time = 5;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 time = 5;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    public int getTime() {
      return time_;
    }

    public static final int SIGN_FIELD_NUMBER = 6;
    private java.lang.Object sign_;
    /**
     * <code>optional string sign = 6;</code>
     *
     * <pre>
     * 验证串
     * </pre>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string sign = 6;</code>
     *
     * <pre>
     * 验证串
     * </pre>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sign = 6;</code>
     *
     * <pre>
     * 验证串
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      usr_ = "";
      platform_ = org.shell.mmo.sample.message.proto.Global.Platform.INNER;
      server_ = 0;
      adult_ = false;
      time_ = 0;
      sign_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, platform_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, server_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, adult_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, time_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSignBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, platform_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, server_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, adult_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, time_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSignBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.shell.mmo.sample.message.proto.ReqLoginLogin}
     *
     * <pre>
     * 登录:参数
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.shell.mmo.sample.message.proto.ReqLoginLogin)
        org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.shell.mmo.sample.message.proto.LogicClient.internal_static_org_shell_mmo_sample_message_proto_ReqLoginLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.shell.mmo.sample.message.proto.LogicClient.internal_static_org_shell_mmo_sample_message_proto_ReqLoginLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin.class, org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin.Builder.class);
      }

      // Construct using org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        usr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        platform_ = org.shell.mmo.sample.message.proto.Global.Platform.INNER;
        bitField0_ = (bitField0_ & ~0x00000002);
        server_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        adult_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        sign_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.shell.mmo.sample.message.proto.LogicClient.internal_static_org_shell_mmo_sample_message_proto_ReqLoginLogin_descriptor;
      }

      public org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin getDefaultInstanceForType() {
        return org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin.getDefaultInstance();
      }

      public org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin build() {
        org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin buildPartial() {
        org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin result = new org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.usr_ = usr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.platform_ = platform_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.server_ = server_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.adult_ = adult_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sign_ = sign_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin) {
          return mergeFrom((org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin other) {
        if (other == org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin.getDefaultInstance()) return this;
        if (other.hasUsr()) {
          bitField0_ |= 0x00000001;
          usr_ = other.usr_;
          onChanged();
        }
        if (other.hasPlatform()) {
          setPlatform(other.getPlatform());
        }
        if (other.hasServer()) {
          setServer(other.getServer());
        }
        if (other.hasAdult()) {
          setAdult(other.getAdult());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasSign()) {
          bitField0_ |= 0x00000020;
          sign_ = other.sign_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.shell.mmo.sample.message.proto.LogicClient.ReqLoginLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object usr_ = "";
      /**
       * <code>optional string usr = 1;</code>
       *
       * <pre>
       * 账号
       * </pre>
       */
      public boolean hasUsr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string usr = 1;</code>
       *
       * <pre>
       * 账号
       * </pre>
       */
      public java.lang.String getUsr() {
        java.lang.Object ref = usr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            usr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string usr = 1;</code>
       *
       * <pre>
       * 账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsrBytes() {
        java.lang.Object ref = usr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string usr = 1;</code>
       *
       * <pre>
       * 账号
       * </pre>
       */
      public Builder setUsr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        usr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string usr = 1;</code>
       *
       * <pre>
       * 账号
       * </pre>
       */
      public Builder clearUsr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        usr_ = getDefaultInstance().getUsr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string usr = 1;</code>
       *
       * <pre>
       * 账号
       * </pre>
       */
      public Builder setUsrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        usr_ = value;
        onChanged();
        return this;
      }

      private org.shell.mmo.sample.message.proto.Global.Platform platform_ = org.shell.mmo.sample.message.proto.Global.Platform.INNER;
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.Platform platform = 2;</code>
       *
       * <pre>
       * 平台
       * </pre>
       */
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.Platform platform = 2;</code>
       *
       * <pre>
       * 平台
       * </pre>
       */
      public org.shell.mmo.sample.message.proto.Global.Platform getPlatform() {
        return platform_;
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.Platform platform = 2;</code>
       *
       * <pre>
       * 平台
       * </pre>
       */
      public Builder setPlatform(org.shell.mmo.sample.message.proto.Global.Platform value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.Platform platform = 2;</code>
       *
       * <pre>
       * 平台
       * </pre>
       */
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000002);
        platform_ = org.shell.mmo.sample.message.proto.Global.Platform.INNER;
        onChanged();
        return this;
      }

      private int server_ ;
      /**
       * <code>optional int32 server = 3;</code>
       *
       * <pre>
       * 服务器
       * </pre>
       */
      public boolean hasServer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 server = 3;</code>
       *
       * <pre>
       * 服务器
       * </pre>
       */
      public int getServer() {
        return server_;
      }
      /**
       * <code>optional int32 server = 3;</code>
       *
       * <pre>
       * 服务器
       * </pre>
       */
      public Builder setServer(int value) {
        bitField0_ |= 0x00000004;
        server_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 server = 3;</code>
       *
       * <pre>
       * 服务器
       * </pre>
       */
      public Builder clearServer() {
        bitField0_ = (bitField0_ & ~0x00000004);
        server_ = 0;
        onChanged();
        return this;
      }

      private boolean adult_ ;
      /**
       * <code>optional bool adult = 4;</code>
       *
       * <pre>
       * 是否成年
       * </pre>
       */
      public boolean hasAdult() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool adult = 4;</code>
       *
       * <pre>
       * 是否成年
       * </pre>
       */
      public boolean getAdult() {
        return adult_;
      }
      /**
       * <code>optional bool adult = 4;</code>
       *
       * <pre>
       * 是否成年
       * </pre>
       */
      public Builder setAdult(boolean value) {
        bitField0_ |= 0x00000008;
        adult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool adult = 4;</code>
       *
       * <pre>
       * 是否成年
       * </pre>
       */
      public Builder clearAdult() {
        bitField0_ = (bitField0_ & ~0x00000008);
        adult_ = false;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <code>optional int32 time = 5;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 time = 5;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>optional int32 time = 5;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000010;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 time = 5;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        time_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sign_ = "";
      /**
       * <code>optional string sign = 6;</code>
       *
       * <pre>
       * 验证串
       * </pre>
       */
      public boolean hasSign() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string sign = 6;</code>
       *
       * <pre>
       * 验证串
       * </pre>
       */
      public java.lang.String getSign() {
        java.lang.Object ref = sign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sign_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sign = 6;</code>
       *
       * <pre>
       * 验证串
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        java.lang.Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sign = 6;</code>
       *
       * <pre>
       * 验证串
       * </pre>
       */
      public Builder setSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sign = 6;</code>
       *
       * <pre>
       * 验证串
       * </pre>
       */
      public Builder clearSign() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sign = 6;</code>
       *
       * <pre>
       * 验证串
       * </pre>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sign_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.shell.mmo.sample.message.proto.ReqLoginLogin)
    }

    static {
      defaultInstance = new ReqLoginLogin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.shell.mmo.sample.message.proto.ReqLoginLogin)
  }

  public interface ResLoginLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.shell.mmo.sample.message.proto.ResLoginLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .org.shell.mmo.sample.message.proto.Error error = 1;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    boolean hasError();
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.Error error = 1;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    org.shell.mmo.sample.message.proto.Global.Error getError();

    /**
     * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
     *
     * <pre>
     * 主角
     * </pre>
     */
    boolean hasLeaderRole();
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
     *
     * <pre>
     * 主角
     * </pre>
     */
    org.shell.mmo.sample.message.proto.Global.LeaderRole getLeaderRole();
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
     *
     * <pre>
     * 主角
     * </pre>
     */
    org.shell.mmo.sample.message.proto.Global.LeaderRoleOrBuilder getLeaderRoleOrBuilder();
  }
  /**
   * Protobuf type {@code org.shell.mmo.sample.message.proto.ResLoginLogin}
   *
   * <pre>
   * 登录:返回值
   * </pre>
   */
  public static final class ResLoginLogin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.shell.mmo.sample.message.proto.ResLoginLogin)
      ResLoginLoginOrBuilder {
    // Use ResLoginLogin.newBuilder() to construct.
    private ResLoginLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResLoginLogin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResLoginLogin defaultInstance;
    public static ResLoginLogin getDefaultInstance() {
      return defaultInstance;
    }

    public ResLoginLogin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResLoginLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.shell.mmo.sample.message.proto.Global.Error value = org.shell.mmo.sample.message.proto.Global.Error.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                error_ = value;
              }
              break;
            }
            case 18: {
              org.shell.mmo.sample.message.proto.Global.LeaderRole.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = leaderRole_.toBuilder();
              }
              leaderRole_ = input.readMessage(org.shell.mmo.sample.message.proto.Global.LeaderRole.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(leaderRole_);
                leaderRole_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.shell.mmo.sample.message.proto.LogicClient.internal_static_org_shell_mmo_sample_message_proto_ResLoginLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.shell.mmo.sample.message.proto.LogicClient.internal_static_org_shell_mmo_sample_message_proto_ResLoginLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin.class, org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin.Builder.class);
    }

    public static com.google.protobuf.Parser<ResLoginLogin> PARSER =
        new com.google.protobuf.AbstractParser<ResLoginLogin>() {
      public ResLoginLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResLoginLogin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResLoginLogin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ERROR_FIELD_NUMBER = 1;
    private org.shell.mmo.sample.message.proto.Global.Error error_;
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.Error error = 1;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.Error error = 1;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    public org.shell.mmo.sample.message.proto.Global.Error getError() {
      return error_;
    }

    public static final int LEADERROLE_FIELD_NUMBER = 2;
    private org.shell.mmo.sample.message.proto.Global.LeaderRole leaderRole_;
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
     *
     * <pre>
     * 主角
     * </pre>
     */
    public boolean hasLeaderRole() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
     *
     * <pre>
     * 主角
     * </pre>
     */
    public org.shell.mmo.sample.message.proto.Global.LeaderRole getLeaderRole() {
      return leaderRole_;
    }
    /**
     * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
     *
     * <pre>
     * 主角
     * </pre>
     */
    public org.shell.mmo.sample.message.proto.Global.LeaderRoleOrBuilder getLeaderRoleOrBuilder() {
      return leaderRole_;
    }

    private void initFields() {
      error_ = org.shell.mmo.sample.message.proto.Global.Error.SYS_ERR;
      leaderRole_ = org.shell.mmo.sample.message.proto.Global.LeaderRole.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, error_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, leaderRole_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, error_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, leaderRole_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.shell.mmo.sample.message.proto.ResLoginLogin}
     *
     * <pre>
     * 登录:返回值
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.shell.mmo.sample.message.proto.ResLoginLogin)
        org.shell.mmo.sample.message.proto.LogicClient.ResLoginLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.shell.mmo.sample.message.proto.LogicClient.internal_static_org_shell_mmo_sample_message_proto_ResLoginLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.shell.mmo.sample.message.proto.LogicClient.internal_static_org_shell_mmo_sample_message_proto_ResLoginLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin.class, org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin.Builder.class);
      }

      // Construct using org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLeaderRoleFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        error_ = org.shell.mmo.sample.message.proto.Global.Error.SYS_ERR;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (leaderRoleBuilder_ == null) {
          leaderRole_ = org.shell.mmo.sample.message.proto.Global.LeaderRole.getDefaultInstance();
        } else {
          leaderRoleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.shell.mmo.sample.message.proto.LogicClient.internal_static_org_shell_mmo_sample_message_proto_ResLoginLogin_descriptor;
      }

      public org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin getDefaultInstanceForType() {
        return org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin.getDefaultInstance();
      }

      public org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin build() {
        org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin buildPartial() {
        org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin result = new org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (leaderRoleBuilder_ == null) {
          result.leaderRole_ = leaderRole_;
        } else {
          result.leaderRole_ = leaderRoleBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin) {
          return mergeFrom((org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin other) {
        if (other == org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin.getDefaultInstance()) return this;
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasLeaderRole()) {
          mergeLeaderRole(other.getLeaderRole());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.shell.mmo.sample.message.proto.LogicClient.ResLoginLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.shell.mmo.sample.message.proto.Global.Error error_ = org.shell.mmo.sample.message.proto.Global.Error.SYS_ERR;
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.Error error = 1;</code>
       *
       * <pre>
       * 错误码
       * </pre>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.Error error = 1;</code>
       *
       * <pre>
       * 错误码
       * </pre>
       */
      public org.shell.mmo.sample.message.proto.Global.Error getError() {
        return error_;
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.Error error = 1;</code>
       *
       * <pre>
       * 错误码
       * </pre>
       */
      public Builder setError(org.shell.mmo.sample.message.proto.Global.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.Error error = 1;</code>
       *
       * <pre>
       * 错误码
       * </pre>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = org.shell.mmo.sample.message.proto.Global.Error.SYS_ERR;
        onChanged();
        return this;
      }

      private org.shell.mmo.sample.message.proto.Global.LeaderRole leaderRole_ = org.shell.mmo.sample.message.proto.Global.LeaderRole.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.shell.mmo.sample.message.proto.Global.LeaderRole, org.shell.mmo.sample.message.proto.Global.LeaderRole.Builder, org.shell.mmo.sample.message.proto.Global.LeaderRoleOrBuilder> leaderRoleBuilder_;
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
       *
       * <pre>
       * 主角
       * </pre>
       */
      public boolean hasLeaderRole() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
       *
       * <pre>
       * 主角
       * </pre>
       */
      public org.shell.mmo.sample.message.proto.Global.LeaderRole getLeaderRole() {
        if (leaderRoleBuilder_ == null) {
          return leaderRole_;
        } else {
          return leaderRoleBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
       *
       * <pre>
       * 主角
       * </pre>
       */
      public Builder setLeaderRole(org.shell.mmo.sample.message.proto.Global.LeaderRole value) {
        if (leaderRoleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          leaderRole_ = value;
          onChanged();
        } else {
          leaderRoleBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
       *
       * <pre>
       * 主角
       * </pre>
       */
      public Builder setLeaderRole(
          org.shell.mmo.sample.message.proto.Global.LeaderRole.Builder builderForValue) {
        if (leaderRoleBuilder_ == null) {
          leaderRole_ = builderForValue.build();
          onChanged();
        } else {
          leaderRoleBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
       *
       * <pre>
       * 主角
       * </pre>
       */
      public Builder mergeLeaderRole(org.shell.mmo.sample.message.proto.Global.LeaderRole value) {
        if (leaderRoleBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              leaderRole_ != org.shell.mmo.sample.message.proto.Global.LeaderRole.getDefaultInstance()) {
            leaderRole_ =
              org.shell.mmo.sample.message.proto.Global.LeaderRole.newBuilder(leaderRole_).mergeFrom(value).buildPartial();
          } else {
            leaderRole_ = value;
          }
          onChanged();
        } else {
          leaderRoleBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
       *
       * <pre>
       * 主角
       * </pre>
       */
      public Builder clearLeaderRole() {
        if (leaderRoleBuilder_ == null) {
          leaderRole_ = org.shell.mmo.sample.message.proto.Global.LeaderRole.getDefaultInstance();
          onChanged();
        } else {
          leaderRoleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
       *
       * <pre>
       * 主角
       * </pre>
       */
      public org.shell.mmo.sample.message.proto.Global.LeaderRole.Builder getLeaderRoleBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLeaderRoleFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
       *
       * <pre>
       * 主角
       * </pre>
       */
      public org.shell.mmo.sample.message.proto.Global.LeaderRoleOrBuilder getLeaderRoleOrBuilder() {
        if (leaderRoleBuilder_ != null) {
          return leaderRoleBuilder_.getMessageOrBuilder();
        } else {
          return leaderRole_;
        }
      }
      /**
       * <code>optional .org.shell.mmo.sample.message.proto.LeaderRole leaderRole = 2;</code>
       *
       * <pre>
       * 主角
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.shell.mmo.sample.message.proto.Global.LeaderRole, org.shell.mmo.sample.message.proto.Global.LeaderRole.Builder, org.shell.mmo.sample.message.proto.Global.LeaderRoleOrBuilder> 
          getLeaderRoleFieldBuilder() {
        if (leaderRoleBuilder_ == null) {
          leaderRoleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.shell.mmo.sample.message.proto.Global.LeaderRole, org.shell.mmo.sample.message.proto.Global.LeaderRole.Builder, org.shell.mmo.sample.message.proto.Global.LeaderRoleOrBuilder>(
                  getLeaderRole(),
                  getParentForChildren(),
                  isClean());
          leaderRole_ = null;
        }
        return leaderRoleBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.shell.mmo.sample.message.proto.ResLoginLogin)
    }

    static {
      defaultInstance = new ResLoginLogin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.shell.mmo.sample.message.proto.ResLoginLogin)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_shell_mmo_sample_message_proto_ReqLoginLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_shell_mmo_sample_message_proto_ReqLoginLogin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_shell_mmo_sample_message_proto_ResLoginLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_shell_mmo_sample_message_proto_ResLoginLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021LogicClient.proto\022\"org.shell.mmo.sampl" +
      "e.message.proto\032\014global.proto\"\227\001\n\rReqLog" +
      "inLogin\022\013\n\003usr\030\001 \001(\t\022>\n\010platform\030\002 \001(\0162," +
      ".org.shell.mmo.sample.message.proto.Plat" +
      "form\022\016\n\006server\030\003 \001(\005\022\r\n\005adult\030\004 \001(\010\022\014\n\004t" +
      "ime\030\005 \001(\005\022\014\n\004sign\030\006 \001(\t\"\215\001\n\rResLoginLogi" +
      "n\0228\n\005error\030\001 \001(\0162).org.shell.mmo.sample." +
      "message.proto.Error\022B\n\nleaderRole\030\002 \001(\0132" +
      "..org.shell.mmo.sample.message.proto.Lea" +
      "derRole"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.shell.mmo.sample.message.proto.Global.getDescriptor(),
        }, assigner);
    internal_static_org_shell_mmo_sample_message_proto_ReqLoginLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_shell_mmo_sample_message_proto_ReqLoginLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_shell_mmo_sample_message_proto_ReqLoginLogin_descriptor,
        new java.lang.String[] { "Usr", "Platform", "Server", "Adult", "Time", "Sign", });
    internal_static_org_shell_mmo_sample_message_proto_ResLoginLogin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_shell_mmo_sample_message_proto_ResLoginLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_shell_mmo_sample_message_proto_ResLoginLogin_descriptor,
        new java.lang.String[] { "Error", "LeaderRole", });
    org.shell.mmo.sample.message.proto.Global.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
